### ISSUE TITLE
Disable react/sort-comp

### ISSUE THREAD

**Issue by levithomason** [TechnologyAdvice/eslint-config-ta#16]
We're doing this repeatedly:

``` js
/* eslint-disable react/sort-comp, react/prop-types */
```

I am proposing that sort-comp has not improved our lives or code as much as it is a pain and slow down.  It also seems to be disabled in tandem with prop-types for flow reasons.

Also see #12, we should update the rules to reflect our practices.

**Comment by davezuko** [comment]
:ghost: 

praise jeebus.
